{
    "InternalException.html": {
        "modified": "2021-07-24 18:49:52.718074",
        "size": "5.52KB",
        "md5": "febaf581530902d14ae89054b8284c94",
        "sha256": "38c1405b0da575db7c914e65a52c134c5b1be63e0b222971916dc7b9a3e6ea58"
    },
    "Metadata": {
        "Content-Encoding": "ISO-8859-1",
        "Content-Type": "text/html; charset=ISO-8859-1",
        "X-Parsed-By": [
            "org.apache.tika.parser.DefaultParser",
            "org.apache.tika.parser.html.HtmlParser"
        ],
        "X-TIKA:content_handler": "ToTextContentHandler",
        "X-TIKA:embedded_depth": "0",
        "X-TIKA:parse_time_millis": "1",
        "dc:title": "Uses of Class org.apache.axis.InternalException (Axis API)",
        "resourceName": "b'InternalException.html'",
        "title": "Uses of Class org.apache.axis.InternalException (Axis API)"
    }
}